# Generated by Django 2.0.4 on 2019-02-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfassignment',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
