# Generated by Django 2.0.4 on 2018-11-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hwfassignment',
            old_name='type',
            new_name='assignment_type',
        ),
    ]
