# Generated by Django 2.1.4 on 2018-12-18 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181105_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(null=True, upload_to='chat_file')),
                ('initial_upload_time', models.DateTimeField(auto_now_add=True)),
                ('initial_upload_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_message', to='data.MessageContent'),
        ),
        migrations.AddField(
            model_name='messagecontent',
            name='addfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_message_content', to='data.MessageFile'),
        ),
        migrations.AddField(
            model_name='messagecontent',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_message_content', to='data.MessageFile'),
        ),
        migrations.AddField(
            model_name='messagecontent',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic_message_content', to='data.MessageFile'),
        ),
    ]
