# Generated by Django 2.0.4 on 2019-02-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190202_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfsubmission',
            name='long_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_pic_submission', to='data.HWFFile'),
        ),
    ]
