# Generated by Django 2.0.4 on 2019-02-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190202_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfsubmission',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hwfsubmission',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
