# Generated by Django 2.0.4 on 2019-02-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_totalmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmarks',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_total_marks', to='data.HWFCourseClass'),
        ),
    ]
