# Generated by Django 2.0.4 on 2019-03-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20190302_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwxtCookieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField(null=True)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
