# Generated by Django 2.0.4 on 2019-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20190302_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfcourseclass',
            name='location_info',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='hwfcourseclass',
            name='time_info',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
