# Generated by Django 2.0.4 on 2019-02-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190201_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfassignment',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
