# Generated by Django 2.0.4 on 2019-02-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190221_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalmarks',
            old_name='total_marks',
            new_name='direct_average',
        ),
        migrations.AddField(
            model_name='totalmarks',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='totalmarks',
            name='weighted_average',
            field=models.FloatField(default=0.0),
        ),
    ]
