# Generated by Django 2.0.4 on 2019-02-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20190221_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
    ]
