# Generated by Django 2.0.4 on 2019-02-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_hostinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='last_request_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
