# Generated by Django 2.0.4 on 2019-02-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20190225_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='last_request_time',
        ),
    ]
