# Generated by Django 2.0.4 on 2019-03-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_jwxtcookieinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwfcourseclass',
            name='semester_info',
        ),
        migrations.AddField(
            model_name='hwfcourseclass',
            name='cached_students_bupt_id',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='hwfcourseclass',
            name='course_serial',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='class_info',
            field=models.TextField(default='[]'),
        ),
    ]
