# Generated by Django 2.0.4 on 2019-03-03 13:00

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20190303_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_code', models.CharField(default=data.models.default_semester_code, max_length=10, unique=True)),
                ('semester_name', models.CharField(default=data.models.default_semester_code, max_length=100, unique=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hwfcourseclass',
            name='location_info',
        ),
        migrations.RemoveField(
            model_name='hwfcourseclass',
            name='time_info',
        ),
        migrations.AddField(
            model_name='hwfcourseclass',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='semester_classes', to='data.Semester'),
            preserve_default=False,
        ),
    ]
