# Generated by Django 2.0.4 on 2019-03-04 15:51

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('data', '0021_auto_20190303_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_users', to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(default=data.models.default_semester_name, max_length=100, unique=True),
        ),
    ]
